// rohd_synth — control over what `generateSynth()` produces and where it goes.
//
// Patches two gaps in `Module.generateSynth()`, both still open upstream.
//
// ## The header (intel/rohd#579)
//
// `generateSynth()` hardcodes a ROHD-branded header:
//
// ```
// /**
//  * Generated by ROHD - www.github.com/intel/rohd
//  * Generation time: 2026-07-28 12:00:00.000 +09:00
//  * ROHD Version: 0.6.9
//  */
// ```
//
// There is no way to change or suppress it. The embedded timestamp means the
// output differs on every run, so generated SystemVerilog cannot be diffed or
// checked into version control cleanly, and identical designs never hash alike.
//
// ## Writing files (intel/rohd#239)
//
// `generateSynth()` returns a `String` and nothing more; saving it is left to
// every caller. Open since 2022.
//
// ## How
//
// `generateSynth()` is only a thin wrapper over `SynthBuilder`, which is public
// API, so both gaps can be closed from outside the package.

import 'dart:io';

import 'package:rohd/rohd.dart';

/// The separator [Module.generateSynth] places between module definitions.
const _defaultSeparator = '\n\n////////////////////\n\n';

/// Generating SystemVerilog without ROHD's fixed comment header, and writing it
/// out.
extension SynthOutput on Module {
  /// Like [Module.generateSynth], but [header] replaces ROHD's built-in comment
  /// block. Defaults to no header at all, which keeps output reproducible.
  ///
  /// [header] is emitted verbatim, so include any trailing blank line you want
  /// between it and the first module definition.
  ///
  /// Must be called after [Module.build], same as [Module.generateSynth].
  String generateSynthWith({
    String header = '',
    String separator = _defaultSeparator,
  }) =>
      header +
      SynthBuilder(this, SystemVerilogSynthesizer())
          .getSynthFileContents()
          .map((f) => f.contents)
          .join(separator);

  /// Writes the whole design to a single `.sv` file at [path], creating parent
  /// directories as needed. Returns the file written.
  File writeSynthFile(
    String path, {
    String header = '',
    String separator = _defaultSeparator,
  }) =>
      File(path)
        ..createSync(recursive: true)
        ..writeAsStringSync(
            generateSynthWith(header: header, separator: separator));

  /// Writes one `.sv` file per module definition into [directory], named after
  /// the module. Returns the files written.
  ///
  /// Useful when downstream tools expect one file per module rather than the
  /// single concatenated blob [Module.generateSynth] produces.
  List<File> writeSynthFiles(String directory, {String header = ''}) =>
      SynthBuilder(this, SystemVerilogSynthesizer())
          .getSynthFileContents()
          .map((f) => File('$directory/${f.name}.sv')
            ..createSync(recursive: true)
            ..writeAsStringSync(header + f.contents))
          .toList(growable: false);
}
